config/routes.rb
Rails.application.routes.draw do

  post 'email_sender/display', to: 'email_sender#display'

  get 'auth/:provider/callback', to: 'auth#callback'
  get 'auth/failure', to: 'auth#failure'
  get 'auth/logout', to: 'auth#logout'

  get 'groups/fishing'
  post 'groups/fishing', to: 'groups#fishingAdd'
  

  get 'groups/camping'
  post 'groups/camping', to: 'groups#campingAdd'

  get 'groups/rapids'
  post 'groups/rapids', to: 'groups#rapidsAdd'

  get 'groups/recreational'
  post 'groups/recreational', to: 'groups#recreationalAdd'

  get 'groups/lakes'
  post 'groups/lakes', to: 'groups#lakesAdd'

  get 'groups/ocean'
  post 'groups/ocean', to: 'groups#oceanAdd'

  post '/logout', to: 'sessions#destroy'

  root "users#index"

  resources :users

  resources :groups

  # get 'sessions/new', to: 'sessions#index'
  # post 'sessions/create', to: 'sessions#create'
  # delete 'sessions/destroy', to: 'sessions#destroy'

# renaming the urls to /login and /logout
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'logout', to: 'auth#logout'

  # get '/auth/:provider/callback', to: 'sessions#create'

  get 'weather', to: 'weather#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
	has_and_belongs_to_many :users, join_table: :groups_users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :is_authenticated?, only: [:update, :edit, :create, :destroy, :fishingAdd, :campingAdd, :rapidsAdd, :recreationalAdd, :lakesAdd, :oceanAdd]
  before_action :is_authenticated?, except: [:index, :new, :create, :show]

  def update
    u = User.find(params[:id])
    u.update(group_params)
    redirect_ro group_path
  end


  def index
  end

  def new
  end

  def show
    @group.users.each do |user|
      @group = Group.find(2)
    end
  end

  def create
  end

  def edit
    @group = Group.find(params[:id])
    @users = User.all
  end

  def destroy
  end

  def fishing
    @fishing = Group.find(1)
    @user_paginator = User.paginate(:page => params[:page], :per_page => 10)
    @user = @user_paginator
  end

  def fishingAdd
    fishing = Group.find(1)
    fishing.users << current_user
  end 

  def camping
    @camping = Group.find(2)
    puts '*************'
    puts @camping.class
    puts '*************'
    @user_paginator = User.paginate(:page => params[:page], :per_page => 10)
    @users = @user_paginator
  end

  def campingAdd
    camping = Group.find(2)
    camping.users << current_user
  end


  def rapids
    @rapids = Group.find(3)
    @user_paginator = User.paginate(:page => params[:page], :per_page => 10)
    @user = @user_paginator
  end

  def rapidsAdd
    rapids = Group.find(3)
    rapids.users << current_user
  end

  def recreational
    @recreational = Group.find(4)
    @user_paginator = User.paginate(:page => params[:page], :per_page => 10)
    @user = @user_paginator
  end

  def recreationalAdd
    recreational = Group.find(4)
    recreational.users << current_user
  end

  def lakes
    @lakes = Group.find(5)
    @user_paginator = User.paginate(:page => params[:page], :per_page => 10)
    @user = @user_paginator
  end

  def lakesAdd
    lakes = Group.find(5)
    lakes.users << current_user
  end

  def ocean
    @ocean = Group.find(6)
    @user_paginator = User.paginate(:page => params[:page], :per_page => 10)
    @user = @user_paginator
  end

  def oceanAdd
    ocean = Group.find(6)
    ocean.users << current_user
  end

  def group_params
    params.require(:group).permit(:name, :group, :info, :user_ids => [])
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/camping.html.erb
<!-- <div class="parallax"><%= image_tag "pic3.jpg", class: "pic" %></div> -->


<h1> Camping Group </h1>


<%= form_tag('/groups/camping', class: "waves-effect waves-light btn") do %>
  
<%= hidden_field_tag 'user_id', 'current_user.id' %>

<%= submit_tag ('Join Camping Group'), data: { confirm: 'You are now apart of the Camping Group' } %>


<% end %>

<div class="container">
</div>
  <%= will_paginate @user_paginator %>

  <% @camping.users.each do |user| %>
    <div class="divider"></div>
    <div class="section row">
      
      <div class="col m6 offset-m1 s6">
        
        <img src="<%= user.picture %>" class="user-img" alt="user image">

          <div class="container user-ctn">
            <div class="user-info">
            <!-- this should link to specific user's page (user_path) -->
            <span><%= link_to(user.name, user_path(user)) %></span>    
              <span>| <%= user.city %></span>
              <span>| <%= user.gender %> | </span>
          
            <p>Skill Level: <%= user.skill_level %></p>
            <div class="truncate"><%= user.more_info %></div>
          </div>
        </div>
      </div>
    </div>
 <% end %>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/fishing.html.erb
<!-- <div class="parallax"><%= image_tag "pic2.jpg", class: "pic" %></div> -->

<h1> Fishing Group </h1>


<%= form_tag('/groups/fishing', class: "waves-effect waves-light btn" ) do %> 
  
<%= hidden_field_tag 'user_id', 'current_user.id' %>

<%= submit_tag ('Join Fishing Group'), data: { confirm: 'You are now apart of the Fishing Group' } %>
<% end %>

<div class="container">
    <%= will_paginate @user_paginator %>
  </div>
<% @fishing.users.each do |user| %>
  <div class="divider"></div>
  <div class="section row">
    
    <div class="col m6 offset-m1 s6">
      
      <img src="<%= user.picture %>" class="user-img" alt="user image">

        <div class="container user-ctn">
          <div class="user-info">
          <!-- this should link to specific user's page (user_path) -->
       		<span><%= link_to(user.name, user_path(user)) %></span>    
            <span>| <%= user.city %></span>
            <span>| <%= user.gender %> | </span>
        
          <p>Skill Level: <%= user.skill_level %></p>
          <div class="truncate"><%= user.more_info %></div>
        </div>
       </div>
    </div>
 <% end %>

app/views/groups/index.html.erb
  <h1 class="groups">Join A Kayak Group</h1>
<div class="parallax-container">
  <div class="parallax"><%= image_tag "pic1.jpg", class: "pic" %> </div>
</div>
<div class="section #b3e5fc light-blue lighten-4">
  <div class="row container" id="container1" >
    <h2 class="header"><%= link_to('Fishing', groups_fishing_path) %></h2>
    <br><a class="waves-effect waves-light btn" id="bttn1" <%= link_to 'join fishing group', groups_fishing_path %></a>
    <p class="grey-text text-darken-3 lighten-3">We are all about fishing while kayaking. Bonus points if we cook the fish afterward.</p>
  </div>
</div>
<div class="parallax-container">
  <div class="parallax"><%= image_tag "pic2.jpg", class: "pic" %></div>
</div>
<div class="section #b3e5fc light-blue lighten-4">
  <div class="row container" id="container2">
    <h2 class="header"><%= link_to('Camping', groups_camping_path) %></h2>
    <br><a class="waves-effect waves-light btn" id="bttn2" <%= link_to 'join camping group', groups_camping_path %></a>
    <p class="grey-text text-darken-3 lighten-3">Do you like camping trips with your kayak? This is the group for you.</p>
  </div>
</div>
<div class="parallax-container">
  <div class="parallax"><%= image_tag "pic3.jpg", class: "pic" %></div>
</div>
<div class="section #b3e5fc light-blue lighten-4">
  <div class="row container" id="container3">
  <h2 class="header"><%= link_to('Rapids', groups_rapids_path) %></h2>
  <br><a class="waves-effect waves-light btn" id="bttn3" <%= link_to 'join rapids group', groups_rapids_path %></a>
  <p class="grey-text text-darken-3 lighten-3">EXTREME!</p>
  </div>
</div>
<div class="parallax-container">
  <div class="parallax"><%= image_tag "pic4.jpg", class: "pic" %></div>
</div>
<div class="section #b3e5fc light-blue lighten-4">
  <div class="row container" id="container3">
    <h2 class="header"><%= link_to('Recreational', groups_recreational_path) %></h2>
    <br><a class="waves-effect waves-light btn" id="bttn4" <%= link_to 'join recreational group', groups_recreational_path %></a>
    <p class="grey-text text-darken-3 lighten-3">Chilling and kayaking, man ... </p>
  </div>
</div>
<div class="parallax-container">
  <div class="parallax"><%= image_tag "pic5.jpg", class: "pic" %></div>
</div>
<div class="section #b3e5fc light-blue lighten-4">
  <div class="row container" id="container4">
  <h2 class="header"><%= link_to('Lakes', groups_lakes_path) %></h2>
  <br><a class="waves-effect waves-light btn" id="bttn5" <%= link_to 'join lakes group', groups_lakes_path %></a>
  <p class="grey-text text-darken-3 lighten-3">This group is for those of you who enjoy swimming while kayaking.</p>
  </div>
</div>
<div class="parallax-container">
  <div class="parallax"><%= image_tag "pic6.jpg", class: "pic" %></div>
</div>
<div class="section #b3e5fc light-blue lighten-4">
  <div class="row container" id="container5">
  <h2 class="header"><%= link_to('Ocean', groups_ocean_path) %></h2>
  <br><a class="waves-effect waves-light btn" id="bttn6" <%= link_to 'join ocean group', groups_ocean_path %></a>
  <p class="grey-text text-darken-3 lighten-3">Want to go whale watching? This is the group for you.</p>
  </div>
</div>
<div class="parallax-container">
  <div class="parallax"><%= image_tag "pic7.jpg", class: "pic" %></div>
</div>

        

app/views/groups/lakes.html.erb
<!-- <img src="https://images.unsplash.com/photo-1468549940493-46152524296c?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=22fd0ceed4703bb1404e4f447d921041" id="lakepic"> -->

<h1> Lakes Group </h1>

<%= form_tag('/groups/lakes', class: "waves-effect waves-light btn") do %>
  
<%= hidden_field_tag 'user_id', 'current_user.id' %>

<%= submit_tag ('join group'), data: { confirm: 'You are now apart of the Lakes Group' } %>

<% end %>

<div class="container">
    <%= will_paginate @user_paginator %>
  </div>
<% @lakes.users.each do |user| %>
  <div class="divider"></div>
  <div class="section row">
    
    <div class="col m6 offset-m1 s6">
      
      <img src="<%= user.picture %>" class="user-img" alt="user image">

        <div class="container user-ctn">
          <div class="user-info">
          <!-- this should link to specific user's page (user_path) -->
       		<span><%= link_to(user.name, user_path(user)) %></span>    
            <span>| <%= user.city %></span>
            <span>| <%= user.gender %> | </span>
        
          <p>Skill Level: <%= user.skill_level %></p>
          <div class="truncate"><%= user.more_info %></div>
        </div>
       </div>
    </div>
 <% end %>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/groups/ocean.html.erb
<!-- <div class="parallax"><%= image_tag "pic7.jpg", class: "pic" %></div> -->

<h1> Ocean Group </h1>


<%= form_tag('/groups/ocean', class:"waves-effect waves-light btn") do %>
  
<%= hidden_field_tag 'user_id', 'current_user.id' %>

<%= submit_tag ('Join Ocean Group'), data: { confirm: 'You are now apart of the Ocean Group' } %>

<% end %>

<div class="container">
    <%= will_paginate @user_paginator %>
  </div>
<% @ocean.users.each do |user| %>
  <div class="divider"></div>
  <div class="section row">
    
    <div class="col m6 offset-m1 s6">
      
      <img src="<%= user.picture %>" class="user-img" alt="user image">

        <div class="container user-ctn">
          <div class="user-info">
          <!-- this should link to specific user's page (user_path) -->
       		<span><%= link_to(user.name, user_path(user)) %></span>    
            <span>| <%= user.city %></span>
            <span>| <%= user.gender %> | </span>
        
          <p>Skill Level: <%= user.skill_level %></p>
          <div class="truncate"><%= user.more_info %></div>
        </div>
       </div>
    </div>
 <% end %>

app/views/groups/rapids.html.erb
<!-- <div class="parallax"><%= image_tag "pic4.jpg", class: "pic" %></div> -->

<h1> Rapids Group </h1>


<%= form_tag('/groups/rapids', class:"waves-effect waves-light btn") do %>
  
<%= hidden_field_tag 'user_id', 'current_user.id' %>

<%= submit_tag ('Join Rapids Group'), data: { confirm: 'You are now apart of the Rapids Group' } %>

<% end %>

<div class="container">
    <%= will_paginate @user_paginator %>
  </div>
<% @rapids.users.each do |user| %>
  <div class="divider"></div>
  <div class="section row">
    
    <div class="col m6 offset-m1 s6">
      
      <img src="<%= user.picture %>" class="user-img" alt="user image">

        <div class="container user-ctn">
          <div class="user-info">
          <!-- this should link to specific user's page (user_path) -->
       		<span><%= link_to(user.name, user_path(user)) %></span>    
            <span>| <%= user.city %></span>
            <span>| <%= user.gender %> | </span>
        
          <p>Skill Level: <%= user.skill_level %></p>
          <div class="truncate"><%= user.more_info %></div>
        </div>
       </div>
    </div>
 <% end %>

app/views/groups/recreational.html.erb
<!-- <div class="parallax"><%= image_tag "pic5.jpg", class: "pic" %></div> -->

<h1> Recreational Group </h1>

<%= form_tag('/groups/recreational', class:"waves-effect waves-light btn")do %>
  
<%= hidden_field_tag 'user_id', 'current_user.id' %>

<%= submit_tag ('Join Recreational Group'), data: { confirm: 'You are now apart of the Recreational Group' } %>

<% end %>

<div class="container">
    <%= will_paginate @user_paginator %>
  </div>
<% @recreational.users.each do |user| %>
  <div class="divider"></div>
  <div class="section row">
    
    <div class="col m6 offset-m1 s6">
      
      <img src="<%= user.picture %>" class="user-img" alt="user image">

        <div class="container user-ctn">
          <div class="user-info">
          <!-- this should link to specific user's page (user_path) -->
       		<span><%= link_to(user.name, user_path(user)) %></span>    
            <span>| <%= user.city %></span>
            <span>| <%= user.gender %> | </span>
        
          <p>Skill Level: <%= user.skill_level %></p>
          <div class="truncate"><%= user.more_info %></div>
        </div>
       </div>
    </div>
 <% end %>

app/views/groups/show.html.erb
<h1>Groups</h1>

<!-- @users should be what you use in the controller, otherwise change it -->
<% @users.each do |user| %>
  <div class="divider"></div>
  <div class="section row">
    
    <div class="col m6 offset-m1 s6">
      
      <a href="<%= user.picture %>" class="" alt="user image"></a>

        <div class="container">
          <p>
          <!-- this should link to specific user's page (user_path) -->
            <span><%= link_to(user.name, user_path(user)) %></span>    
            <span>| <%= user.city %></span>
            <span>| <%= user.gender %> | </span>
          </p>
          <p>Skill Level: <%= user.skill_level %></p>
          <div><%= user.more_info %></div>
       </div>
    </div>

    <div class="col m3 offset-m2 s6">
    <button class="btn send-msg">Contact</button>
    </div>

    <% @group.users.each do |user| %>
  <p><%= link_to(user.name, user_path) %></p>
​
<% end %>

  </div>